### ISSUE TITLE
[Bug] Limit cases visibility to cases investigators

### ISSUE THREAD

**Issue by jlequen** [SITH-Project/SITH-Security-Incident-Tracker-and-Handler#3]
A user who is not the "investigator" of a case should not see this case in the list of cases

**Comment by a-hebert** [comment]
Close with [move entity config to .yaml](https://forge.tedomum.net/sith-project/sith-back-incident-tracker-and-handler/-/commit/9ff26f6413bd4cc74b5a89e4e00b3c3b800d0732)
